# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SSCycleScrollDemo' do
  use_frameworks!
  pod 'SSCycleScrollView', :path => '../SSCycleScrollView'
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0' # or '3.0'
        end
    end
end
