# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SSCycleScrollDemo' do
  use_frameworks!
  pod 'SSCycleScrollView', :path => '../SSCycleScrollView'
end
