# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'SSCycleScrollView' do
  use_frameworks!
  pod 'SDWebImage'
  pod 'SDWebImage/WebP'

  # Pods for SSCycleScrollView

end
